### ISSUE TITLE
Usability stuff

### ISSUE THREAD

**Issue by ThomasPietrzak** [grumpycoders/papan#79]
#Todo 

- [x] display lobby name in lobby list
- [ ] display player name in player slot
- [ ] list connected player in lobby
- [ ] remove game list button in main window
- [ ] server status in server list
- [ ] add server : HTTP by default (+ tooltip)
- [ ] remove public switch for non-owner
- [ ] close lobby
